@startuml
interface CustomAggregate {
  iterator() : CustomIterator
}
interface CustomIterator
class BookShelfIterator
class BookShelf
class Book

BookShelfIterator --|> CustomIterator : implements

BookShelf --|> CustomAggregate : implements

BookShelf o-- Book : contains

CustomAggregate ..> CustomIterator : creates
@enduml
